
services:
  frontend_production:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3003:3003"  # Cambia el puerto si es necesario
    networks:
      - planning_poker_default

networks:
  planning_poker_default:
    external: true